// V14 meteor-interior loading shell (METEOR_ARRIVAL_SEQUENCE_SPEC.md).
// Canvas overlay shader: warm-lit rock interior + pulsing crack glow, breaking open
// plate-by-plate (Voronoi plates, center-out order baked in the texture's A channel) when
// _OpenProgress rises. Fed a packed texture generated by MeteorShellOverlay
// (R = rock FBM, G = crack mask, B = crack halo for light bleed, A = plate dissolve order).
// Plain CG UI shader on purpose — ScreenSpaceOverlay canvases bypass URP scene rendering.
Shader "UI/MeteorShellOverlay"
{
    Properties
    {
        _MainTex ("Packed (R rock, G crack, B halo, A plate order)", 2D) = "white" {}
        _RockColor ("Rock Color", Color) = (0.50, 0.40, 0.32, 1)
        _RockDeepColor ("Rock Deep Color", Color) = (0.21, 0.17, 0.14, 1)
        _CrackColor ("Crack Glow Color", Color) = (1.0, 0.45, 0.12, 1)
        _CrackGlow ("Crack Glow Intensity", Range(0, 4)) = 1.1
        _CrackBleed ("Crack Light Bleed", Range(0, 2)) = 0.7
        _PulseSpeed ("Pulse Speed", Float) = 2.2
        _OpenProgress ("Open Progress", Range(0, 1)) = 0
        _Flare ("Flare", Range(0, 1)) = 0
    }

    SubShader
    {
        Tags
        {
            "Queue" = "Overlay"
            "IgnoreProjector" = "True"
            "RenderType" = "Transparent"
            "PreviewType" = "Plane"
        }

        Cull Off
        Lighting Off
        ZWrite Off
        ZTest Always
        Blend SrcAlpha OneMinusSrcAlpha

        Pass
        {
            CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #include "UnityCG.cginc"

            struct appdata
            {
                float4 vertex : POSITION;
                float2 uv : TEXCOORD0;
                fixed4 color : COLOR;
            };

            struct v2f
            {
                float4 vertex : SV_POSITION;
                float2 uv : TEXCOORD0;
                fixed4 color : COLOR;
            };

            sampler2D _MainTex;
            fixed4 _RockColor;
            fixed4 _RockDeepColor;
            fixed4 _CrackColor;
            float _CrackGlow;
            float _CrackBleed;
            float _PulseSpeed;
            float _OpenProgress;
            float _Flare;

            v2f vert(appdata v)
            {
                v2f o;
                o.vertex = UnityObjectToClipPos(v.vertex);
                o.uv = v.uv;
                o.color = v.color;
                return o;
            }

            fixed4 frag(v2f i) : SV_Target
            {
                // Slight outward zoom while opening — the surviving plates grow toward the
                // screen edges, reading as debris passing the emerging player.
                float2 uv = (i.uv - 0.5) * (1.0 - 0.14 * _OpenProgress) + 0.5;

                fixed4 shellTex = tex2D(_MainTex, uv);
                float rockL = shellTex.r;
                float crack = shellTex.g;
                float halo = shellTex.b;
                float plateOrder = shellTex.a;
                float radial = saturate(distance(uv, float2(0.5, 0.5)) / 0.7071);

                // Interior read: lit rock, gently darker toward the screen edges — never black;
                // the cracks are the light source, so their halo warms the nearby plate surface.
                float pulse = 0.55 + 0.45 * sin(_Time.y * _PulseSpeed + rockL * 6.2831);
                float3 rock = lerp(_RockDeepColor.rgb, _RockColor.rgb, rockL);
                rock *= lerp(1.0, 0.65, smoothstep(0.35, 1.0, radial));
                rock += _CrackColor.rgb * halo * _CrackBleed * (0.55 + 0.45 * pulse);

                float glowAmt = crack * (_CrackGlow * pulse + _Flare * 3.0);
                float3 col = rock + _CrackColor.rgb * glowAmt;

                // Plate-by-plate dissolve: each plate holds until the sweep reaches its baked
                // order, then erodes internally over a short window (rock noise = erosion grain),
                // heating up just before it goes.
                float p = _OpenProgress * 1.12; // sweep past the max order (0.88) + window (0.12)
                float pixelGate = plateOrder + rockL * 0.12;
                float alpha = 1.0 - smoothstep(pixelGate - 0.03, pixelGate + 0.03, p);

                // Pre-burn heat: the plate brightens toward the crack color as its moment nears.
                float heat = smoothstep(pixelGate - 0.12, pixelGate, p) * alpha;
                col += _CrackColor.rgb * heat * 1.6;

                // Burning front: the eroding boundary itself flares bright — departing plates
                // read as burning away, not fading out. Peaks mid-transition (alpha = 0.5).
                float front = (1.0 - alpha) * alpha * 4.0;
                col += _CrackColor.rgb * front * 2.5;

                return fixed4(col, alpha) * i.color;
            }
            ENDCG
        }
    }
}
